name: Cypress parallel tests

on: 
  push:
    branches:
      - local
  
jobs:
  browserStack_job:
    name: 'BrowserStack setup on Ubuntu'
    runs-on: ubuntu-latest  # Can be self-hosted runner also
    steps:
    - name: 'BrowserStack Env Setup'  # Invokes the setup-env action
      uses: browserstack/github-actions/setup-env@master
      with:
        username:  ${{ secrets.BROWSERSTACK_USERNAME }}
        access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    - name: 'BrowserStack Local Tunnel Setup'  # Invokes the setup-local action
      uses: browserstack/github-actions/setup-local@master
      with:
        local-testing: start
        local-identifier: random
        local-logging-level: all-logs
        local-args: --parallel-runs 2
    - name: 'Checkout the repository'
      uses: actions/checkout@v3

    - name: 'Building web application to be tested'
      run: npm install

    - name: 'Running application under test'
      run: npm run dev

    - name: 'Running test on BrowserStack'  
      run: npm run run:specs

    - name: 'BrowserStackLocal Stop'  # Terminating the BrowserStackLocal tunnel connection
      uses: browserstack/github-actions/setup-local@master
      with:
        local-testing: stop

     - name: screenshots section
      uses: actions/upload-artifact@master
      with:
        name: screenshots
        path: cypress/screenshots
        if: failure()
    # video should always be generated
    - name: videos section
      uses: actions/upload-artifact@master
      with:
        name: videos
        path: cypress/videos