name: Cypress parallel tests

on: 
  push:
    branches:
      - local
  
jobs:
  browserStack_job:
    name: 'BrowserStack setup on Ubuntu'
    runs-on: ubuntu-latest  # Can be self-hosted runner also
    steps:
    - name: 'BrowserStack Env Setup'  # Invokes the setup-env action
      uses: browserstack/github-actions/setup-env@master
      with:
        username:  ${{ secrets.BROWSERSTACK_USERNAME }}
        access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    - name: 'BrowserStack Local Tunnel Setup'  # Invokes the setup-local action
      uses: browserstack/github-actions/setup-local@master
      with:
        local-testing: start
        local-identifier: random
        local-logging-level: all-logs
        local-args: --parallel-runs 2
    - name: Install NPM
      runs-on: ubuntu-latest
      uses: actions/checkout@v3
    - name: Use Node.js v16
      uses: actions/setup-node@v3
      with:
          node-version: 16
    - name: Cypress job
      runs-on: ubuntu-latest
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run Cypress E2E Tests
      uses: cypress-io/github-action@v4
      with:
        start: npm start
        wait-on: 'http://localhost:8080'
        wait-on-timeout: 60
        #install-command: yarn --frozen-lockfile --silent
        spec: cypress/e2e/2-advanced-examples/*.cy.js
    - name: 'BrowserStackLocal Stop'  # Terminating the BrowserStackLocal tunnel connection
      uses: browserstack/github-actions/setup-local@master
      with:
        local-testing: stop
    - uses: actions/upload-artifact@master
      with:
        name: screenshots
        path: cypress/screenshots
        if: failure()
    # video should always be generated
    - uses: actions/upload-artifact@master
      with:
        name: videos
        path: cypress/videos
